### ISSUE TITLE
Segfault in 

### ISSUE THREAD

**Issue by Mindavi** [merbanan/rtl_433#1177]
Segfault in baseband. Input samples: 
[samples.zip](https://github.com/merbanan/rtl_433/files/3765989/samples.zip)

```
ASAN:DEADLYSIGNAL
=================================================================
==2856==ERROR: AddressSanitizer: SEGV on unknown address 0x7f1ca46fa802 (pc 0x5562aa4e4967 bp 0x7fffd19734e0 sp 0x7fffd1973490 T0)
==2856==The signal is caused by a READ memory access.
    #0 0x5562aa4e4966 in baseband_low_pass_filter rtl_433/src/baseband.c:142
    #1 0x5562aa5837e7 in sdr_callback rtl_433/src/rtl_433.c:312
    #2 0x5562aa5a2b27 in main rtl_433/src/rtl_433.c:1359
    #3 0x7f1aa9c02b96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)
    #4 0x5562aa4dd0f9 in _start (/usr/local/bin/rtl_433+0x1aa0f9)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV rtl_433/src/baseband.c:142 in baseband_low_pass_filter
==2856==ABORTING
```

**Comment by zuckschwerdt** [comment]
Oh, ok, I get it. The sample buffer is smaller than a single sample (but not zero), this rounds down to zero. I'll fix this shortly.
