### ISSUE TITLE
Plugin error after start

### ISSUE THREAD

**Issue by oldbug62** [merbanan/rtl_433#2255]
Im using RTL-SDR with SDR-v1.0.0.1905 an becam this error when i start the plugin:

System.IO.FileNotFoundException: 
File name: 'SDRSharpMerged, Version=1.0.0.1784, Culture=neutral, PublicKeyToken=null'
   at SDRSharp.Rtl_433.Rtl_433_Processor.NotifyPropertyChangedHandler(Object sender, PropertyChangedEventArgs e)
   at System.ComponentModel.PropertyChangedEventHandler.Invoke(Object sender, PropertyChangedEventArgs e)
   at SDRSharp.SharpControlProxy.PropertyChangedEventHandler(Object sender, PropertyChangedEventArgs e)
   at SDRSharp.MainForm.ResumePropertyNotifications()
   at SDRSharp.MainForm.ResetFrequency(Int64 frequency, Int64 centerFrequency)
   at SDRSharp.MainForm.UpdateTuningStyle()
   at SDRSharp.SharpControlProxy.set_TuningStyle(TuningStyle value)
   at SDRSharp.Rtl_433.Rtl_433_Processor.setFrequency()
   at SDRSharp.Rtl_433.Rtl_433_Processor.set_FrequencyRtl433(Int64 value)
   at SDRSharp.Rtl_433.Rtl_433_Panel.processParameterOnStart()
   at SDRSharp.Rtl_433.Rtl_433_Panel.Start(Boolean senderRadio)
   at SDRSharp.Rtl_433.Rtl_433_Panel.buttonStartStop_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

**Comment by zuckschwerdt** [comment]
You need to ask the plugin author or maybe SDRSharp.
I guess https://github.com/marco402/plugin-Rtl433-for-SdrSharp or https://github.com/marco402/Rtl_433_dll-for-plugin-SdrSharp
